[wokwi]
version = 1
elf = "../.pio/build/q1/firmware.elf"
firmware = "../.pio/build/q1/firmware.bin"

# Configuração de rede para MQTT
[[net.forward]]
from = "localhost:1883"
to = "172.208.54.189:1883"
protocol = "tcp"